### ISSUE TITLE
Bug when calling builtins.next on builtins.map

### ISSUE THREAD

**Issue by Algebra8** [tdakkota/sun#14]
When calling `builtins.next` on a `builtins.map` object, we get unexpected behavior.

With the current implementation of `map` in tag `v0.2.0-2-g0838055`, we have:

```starlark
    def f(_a):
        return _a
    
    m = map(f, [1, 2, 3])
    print(next(m))      # 1
    print(next(m))      # 1
    print(next(m))      # 1
```
While in Python, the expected behavior is the following:

```bash
>>> def f(a):
...     return a
...
>>> m = map(f, [1, 2, 3])
>>> next(m)
1
>>> next(m)
2
>>> next(m)
3
```

The issue seems to be due to two factors:

1. [`next` will call iterable.Iterate()](https://github.com/tdakkota/sun/blob/master/next.go#L30) upon each call.
2. [`map` will create a new slice of iterators](https://github.com/tdakkota/sun/blob/master/map.go#L72) upon call to `Iterate`.

Since 1. seems like the correct implementation for `next`, i.e. we shouldn't be storing states of iterators globally so the current implementation seems correct, the issue probably has to do with `map`.

One solution is to extract all iterators for `map` in `func map_` and store them as a ~~reference~~ copy to the map object.

Any thoughts :)?

**Comment by Algebra8** [comment]
Also, I have an implementation for `islice` but since it is subject to the same issues as described above for `map`, I will hold off until we find a solution to this issue before making a PR.

**Comment by tdakkota** [comment]
I think `map` object should store `iterator` values, not `iterable`.

> One solution is to extract all iterators for map in func map_ and store them as a reference copy to the map object.

I think this is the only solution.

Thank you for finding this bug!
